apiVersion: apps/v1beta1
kind: Deployment
metadata: 
  name: mongo-limit-pod-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: mongo-limit-demo
    spec:
      containers:
      - name: mongo-limit-demo-pod
        image: mongo
        ports:
        - containerPort: 27017
        resources:
          limits:
            cpu: "50m"
            memory: "128Mi"
