apiVersion: apps/v1beta1
kind: Deployment
metadata: 
  name: mongo-pod-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: mongo-demo
    spec:
      containers:
      - name: mongo-demo-pod
        image: mongo
        ports:
        - containerPort: 27017
