apiVersion: apps/v1beta1
kind: Deployment
metadata: 
  name: pod-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo-pod
        image: busybox
        args:
          - sleep
          - "1000000"
