apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-service
  name: mongo-service
spec:
  clusterIP: 10.111.140.107
  ports:
    - port: 80
      protocol: TCP
      targetPort: 27017
  selector:
    app: mongo-demo
